default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: img_processor_api_development

test:
  <<: *default
  database: img_processor_api_test

production:
  <<: *default
  database: img_processor_api_production
  username: img_processor_api
  password: <%= ENV['IMG_PROCESSOR_API_DATABASE_PASSWORD'] %>
