# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4408ca00c2699b4fa77f419259728ad92ce77e737d53691255290affee9ec78ea7b548b784aa2d92de6a521575e6703ae6136632c6280bb2ea5461f30c6e067e

test:
  secret_key_base: a7d979c4aee5c90c978b152ce4bd4237689484d52cb62b76fc0633bf8e0a712269294196e5aff26482c88c8665ea9f4477c7809a2a9db9908bb61a77e12a84be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
